# 02_eda
Exploratory Data Analysis on RECS 2020 CSV from S3

In [5]:
import pandas as pd, sagemaker

sess   = sagemaker.Session()
bucket = sess.default_bucket()
uri    = f"s3://{bucket}/recs/recs2020.csv"

data = pd.read_csv(uri)
data.head()

,DOEID,REGIONC,DIVISION,STATE_FIPS,state_postal,state_name,BA_climate,IECC_climate_code,UATYP10,HDD65,...,EVCHRGHOME,EVCHRGAPT,EVCHRGWKS,EVCHRGBUS,EVCHRGMUNI,EVCHRGDLR,EVCHRGHWY,EVCHRGOTH,EVHOMEAMT,EVCHRGTYPE
0,100001,WEST,Mountain South,35,NM,New Mexico,Mixed-Dry,4B,U,3844,...,-2.0,-2,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0
1,100002,SOUTH,West South Central,5,AR,Arkansas,Mixed-Humid,4A,U,3766,...,-2.0,-2,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0
2,100003,WEST,Mountain South,35,NM,New Mexico,Mixed-Dry,4B,U,3819,...,-2.0,-2,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0
3,100004,SOUTH,South Atlantic,45,SC,South Carolina,Mixed-Humid,3A,U,2614,...,-2.0,-2,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0
4,100005,NORTHEAST,Middle Atlantic,34,NJ,New Jersey,Mixed-Humid,4A,U,4219,...,-2.0,-2,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18496 entries, 0 to 18495
Columns: 799 entries, DOEID to EVCHRGTYPE
dtypes: float64(243), int64(549), object(7)
memory usage: 112.7+ MB

In [9]:
data.describe()

,DOEID,STATE_FIPS,HDD65,CDD65,HDD30YR_PUB,CDD30YR_PUB,TYPEHUQ,CELLAR,CRAWL,CONCRETE,...,EVCHRGHOME,EVCHRGAPT,EVCHRGWKS,EVCHRGBUS,EVCHRGMUNI,EVCHRGDLR,EVCHRGHWY,EVCHRGOTH,EVHOMEAMT,EVCHRGTYPE
count,18496.000000,18496.000000,18496.000000,18496.000000,18496.000000,18496.000000,18496.000000,18496.000000,18496.000000,18496.000000,...,18485.000000,18496.000000,18434.000000,18428.000000,18424.000000,18421.000000,18424.000000,18432.000000,18486.000000,18487.000000
mean,109248.500000,28.473994,4271.806607,1525.515517,4679.407169,1309.878785,2.547145,-0.115647,-0.252487,-0.175984,...,-1.957750,-1.968534,-1.973093,-1.972976,-1.975250,-1.976169,-1.975630,-1.972331,-1.950557,-1.955969
std,5339.479625,15.992746,2329.457038,1143.238380,2338.516332,988.472131,1.119777,1.143162,1.058109,1.108549,...,0.346716,0.252127,0.246789,0.251823,0.231193,0.223308,0.227088,0.255575,0.459846,0.393757
min,100001.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-2.000000,-2.000000,-2.000000,...,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
25%,104624.750000,15.000000,2433.750000,814.000000,2897.750000,601.000000,2.000000,0.000000,0.000000,0.000000,...,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
50%,109248.500000,28.000000,4396.500000,1179.000000,4825.000000,1020.000000,2.000000,0.000000,0.000000,0.000000,...,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
75%,113872.250000,42.000000,5810.250000,1805.000000,6290.000000,1703.000000,3.000000,1.000000,0.000000,1.000000,...,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
max,118496.000000,56.000000,17383.000000,5534.000000,16071.000000,4905.000000,5.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,2.000000